#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 15, 2018 02:06:38 PM WIB  platform: Linux
#    Oct 15, 2018 04:03:52 PM WIB  platform: Linux
import threading
import sys
##from multiprocessing import Process
##sys.path.insert(0, 'MiBand2/')
##import time
##from base import MiBand2
##from constants import ALERT_TYPES
##
###MAC ADDRESS MI BAND 2
##MAC = 'D6:EC:F2:B3:70:BA'
import time 
import coba
import os
import RPi.GPIO as GPIO
##import thread

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def recap():
    print('coba_support.recap')
    sys.stdout.flush()
    import recap
    recap.create_Treadmill(root, 'new')
    
state = False
# Our time structure [min, sec, centsec]
timer = [0, 0, 0]
# The format is padding all the 
pattern = '{0:02d}:{1:02d}:{2:02d}'

# Default Speed is 1.0 km/h
speed = 1.0

def run_treadmill():
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(17, GPIO.OUT)
    GPIO.output(17, GPIO.LOW)

    time.sleep(0.2)
##    root.after(250)

    GPIO.output(17, GPIO.HIGH)
    GPIO.cleanup()
    
    w.speed_val.configure(text=speed)

def update_timeText():
    if (state):
        global timer
        global root
        # Every time this function is called, 
        # we will increment 1 centisecond (1/100 of a second)
        timer[2] += 1
        
        # Every 100 centisecond is equal to 1 second
        if (timer[2] >= 100):
            timer[2] = 0
            timer[1] += 1
        # Every 60 seconds is equal to 1 min
        if (timer[1] >= 60):
            timer[0] += 1
            timer[1] = 0
        # We create our time string here
        timeString = pattern.format(timer[0], timer[1], timer[2])
        w.timer.configure(text=timeString)
    root.after(10,update_timeText)

##state = False
### Our time structure [min, sec, centsec]
##timer = [0, 0, 0]
### The format is padding all the 
##pattern = '{0:02d}:{1:02d}:{2:02d}'

def data():
##    while True:
    if(state):
        fp = open('log.txt', 'r',os.O_NONBLOCK).read()
        lines = fp.split('\n')
        batas = len(lines)-2

        waktu = []
        bpm = []
        step = []

        for line in lines[batas:]:
            if len(line)>= 1:
                a, b, c = line.split(',')
            waktu.append(str(a))
            bpm.append(str(b))
            step.append(str(c))
##        bpm = bpm[1]
##        step = step[1]
        w.hr_val.configure(text=bpm[1])
        w.step_value.configure(text=step[1])
        print (bpm[1],step[1])
##    time.sleep(2.3)
        root.after(1000,data)

##start = False
def start():
    print('coba_support.start')
    sys.stdout.flush()
    run_treadmill()
##    time.sleep(2.5)
##    global start
##    start = True
    global state
    state = True
##    t1=threading.Thread(target=update_timeText)
##    t2=threading.Thread(target=data)
##    t1.start()
##    t1.join()
    
    update_timeText()
##    p1 = Process(target = update_timeText)
##    p1.start()
##    p1.join()
    w.start.configure(text="Finish", command=finish)
##    t2.start()
##    t2.join()
##    w.hr_val.configure(text=bpm[1])
##    w.step_value.configure(text=step[1])
##    thread.start_new_thread(data())
    data()
##    p2 = Process(target = data)
##    p2.start()
##    p1.join()
##    p2.join()
    

def finish():
    print('coba_support.finish')
    sys.stdout.flush()
    run_treadmill()
    global state
    state = False
    update_timeText()
    data()
    w.start.configure(text="Restart", command=reset)
    
def reset():
    global timer
    timer = [0, 0, 0]
    w.timer.configure(text='00:00:00')
    w.hr_val.configure(text='0')
    w.step_value.configure(text='0')
    w.speed_val.configure(text='0')
    w.start.configure(text="Start", command=start)
    
def speed_down():
    print('coba_support.speed_down')
    sys.stdout.flush()
    
    global speed
##    global start
    if speed > 1.0 and state == True:
        speed = speed - 0.1
        speed = round(speed,1)
        w.speed_val.configure(text=speed)
    
        GPIO.setmode(GPIO.BCM)
        GPIO.setup(27, GPIO.OUT)
        GPIO.output(27, GPIO.LOW)

        time.sleep(0.10)
##        root.after(250, speed_down)

        GPIO.output(27, GPIO.HIGH)
        GPIO.cleanup()
    

def speed_up():
    print('coba_support.speed_up')
    sys.stdout.flush()
    global start
    start = True
    global speed
    if (state):
        speed = speed + 0.1
        speed = round(speed,1)
        w.speed_val.configure(text=speed)
    
        GPIO.setmode(GPIO.BCM)
        GPIO.setup(22, GPIO.OUT)
        GPIO.output(22, GPIO.LOW)
##        root.after(250, speed_up)
        time.sleep(0.10)
        GPIO.output(22, GPIO.HIGH)
        GPIO.cleanup()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import coba
    coba.vp_start_gui()







